In [1]:
import os

zillow_folder = "../data/raw/zillow"

print("Current working directory:")
print(os.getcwd())

print("\nFiles in Zillow folder:")
print(os.listdir(zillow_folder))

Current working directory:
/Users/alphabook/Desktop/RezvanProjects/Case2/notebooks

Files in Zillow folder:
['Metro_new_con_median_sale_price_uc_sfrcondo_month.csv', 'Metro_median_sale_price_now_uc_sfrcondo_month.csv', 'Metro_sales_count_now_uc_sfrcondo_month.csv', 'Metro_new_con_sales_count_raw_uc_sfrcondo_month.csv', 'Metro_mlp_uc_sfrcondo_sm_month.csv', 'Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv', 'Metro_new_listings_uc_sfrcondo_sm_month.csv', 'Metro_invt_fs_uc_sfrcondo_sm_month.csv']

In [2]:
import pandas as pd

zhvi_path = "../data/raw/zillow/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv"
zhvi = pd.read_csv(zhvi_path)

print("Shape:", zhvi.shape)
print("\nColumns:")
print(zhvi.columns.tolist())

zhvi.head()

Shape: (895, 319)

Columns:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31', '2000-09-30', '2000-10-31', '2000-11-30', '2000-12-31', '2001-01-31', '2001-02-28', '2001-03-31', '2001-04-30', '2001-05-31', '2001-06-30', '2001-07-31', '2001-08-31', '2001-09-30', '2001-10-31', '2001-11-30', '2001-12-31', '2002-01-31', '2002-02-28', '2002-03-31', '2002-04-30', '2002-05-31', '2002-06-30', '2002-07-31', '2002-08-31', '2002-09-30', '2002-10-31', '2002-11-30', '2002-12-31', '2003-01-31', '2003-02-28', '2003-03-31', '2003-04-30', '2003-05-31', '2003-06-30', '2003-07-31', '2003-08-31', '2003-09-30', '2003-10-31', '2003-11-30', '2003-12-31', '2004-01-31', '2004-02-29', '2004-03-31', '2004-04-30', '2004-05-31', '2004-06-30', '2004-07-31', '2004-08-31', '2004-09-30', '2004-10-31', '2004-11-30', '2004-12-31', '2005-01-31', '2005-02-28', '2005-03-31', '2005-04-30', '2005-05-31', '2005-06-30', '2005-07-31', '2005-08-31', '2005-09-30', '2005-10-31', '2005-11-30', '2005-12-31', '2006-01-31', '2006-02-28', '2006-03-31', '2006-04-30', '2006-05-31', '2006-06-30', '2006-07-31', '2006-08-31', '2006-09-30', '2006-10-31', '2006-11-30', '2006-12-31', '2007-01-31', '2007-02-28', '2007-03-31', '2007-04-30', '2007-05-31', '2007-06-30', '2007-07-31', '2007-08-31', '2007-09-30', '2007-10-31', '2007-11-30', '2007-12-31', '2008-01-31', '2008-02-29', '2008-03-31', '2008-04-30', '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31', '2008-09-30', '2008-10-31', '2008-11-30', '2008-12-31', '2009-01-31', '2009-02-28', '2009-03-31', '2009-04-30', '2009-05-31', '2009-06-30', '2009-07-31', '2009-08-31', '2009-09-30', '2009-10-31', '2009-11-30', '2009-12-31', '2010-01-31', '2010-02-28', '2010-03-31', '2010-04-30', '2010-05-31', '2010-06-30', '2010-07-31', '2010-08-31', '2010-09-30', '2010-10-31', '2010-11-30', '2010-12-31', '2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30', '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31', '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31', '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31', '2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30', '2013-05-31', '2013-06-30', '2013-07-31', '2013-08-31', '2013-09-30', '2013-10-31', '2013-11-30', '2013-12-31', '2014-01-31', '2014-02-28', '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31', '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28']

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
0,102001,0,United States,country,NaN,121066.152956,121279.147130,121543.291267,122109.828593,122761.845131,...,358275.968224,357665.098303,357242.876410,357017.595555,357256.667089,357686.423395,358355.292319,359137.808336,359884.379965,360590.988249
1,394913,1,"New York, NY",msa,NY,216280.796610,217199.867965,218127.451578,220007.094908,221953.530668,...,686494.959066,687957.664142,689119.941396,689903.028184,691291.361808,693606.472034,696919.534309,700309.679669,703346.479016,706888.193139
2,753899,2,"Los Angeles, CA",msa,CA,221540.469091,222364.880724,223462.989157,225647.856057,228037.415487,...,947802.390588,943448.992297,940857.264784,939786.105392,940842.701541,943258.565513,946575.492297,950534.811318,953064.414891,954296.088135
3,394463,3,"Chicago, IL",msa,IL,151333.694136,151473.785052,151740.590668,152404.336737,153202.743421,...,327362.694469,327718.682483,328546.457616,329528.522924,330843.224170,332130.068337,333656.410070,335364.951509,336962.703562,338685.299108
4,394514,4,"Dallas, TX",msa,TX,128246.740882,128303.862429,128369.529494,128540.059965,128764.899721,...,370409.953287,368034.578505,366008.241036,364639.606059,363989.425471,363639.156361,363374.226561,363155.465003,362719.853605,362141.885524

In [3]:
id_cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]
date_cols = [c for c in zhvi.columns if c not in id_cols]

zhvi_long = zhvi.melt(
    id_vars=id_cols,
    value_vars=date_cols,
    var_name="month",
    value_name="zhvi"
)

zhvi_long["month"] = pd.to_datetime(zhvi_long["month"])
zhvi_long["zhvi"] = pd.to_numeric(zhvi_long["zhvi"], errors="coerce")

zhvi_long = zhvi_long.rename(columns={"RegionName": "metro"})
zhvi_long = zhvi_long[["metro", "StateName", "month", "zhvi"]]

zhvi_long.head()

             metro StateName      month           zhvi
0    United States       NaN 2000-01-31  121066.152956
1     New York, NY        NY 2000-01-31  216280.796610
2  Los Angeles, CA        CA 2000-01-31  221540.469091
3      Chicago, IL        IL 2000-01-31  151333.694136
4       Dallas, TX        TX 2000-01-31  128246.740882

In [4]:
zhvi_long = zhvi_long[zhvi_long["metro"] != "United States"].copy()
zhvi_long = zhvi_long.reset_index(drop=True)

zhvi_long.head()

             metro StateName      month           zhvi
0     New York, NY        NY 2000-01-31  216280.796610
1  Los Angeles, CA        CA 2000-01-31  221540.469091
2      Chicago, IL        IL 2000-01-31  151333.694136
3       Dallas, TX        TX 2000-01-31  128246.740882
4      Houston, TX        TX 2000-01-31  123760.225221

In [5]:
print("Rows:", len(zhvi_long))
print("Unique metros:", zhvi_long["metro"].nunique())
print("Date range:", zhvi_long["month"].min(), "to", zhvi_long["month"].max())

Rows: 280716
Unique metros: 894
Date range: 2000-01-31 00:00:00 to 2026-02-28 00:00:00

In [6]:
msp_path = "../data/raw/zillow/Metro_median_sale_price_now_uc_sfrcondo_month.csv"
msp = pd.read_csv(msp_path)

print("Shape:", msp.shape)
print("\nColumns:")
print(msp.columns.tolist())

msp.head()

Shape: (301, 222)

Columns:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', '2008-02-29', '2008-03-31', '2008-04-30', '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31', '2008-09-30', '2008-10-31', '2008-11-30', '2008-12-31', '2009-01-31', '2009-02-28', '2009-03-31', '2009-04-30', '2009-05-31', '2009-06-30', '2009-07-31', '2009-08-31', '2009-09-30', '2009-10-31', '2009-11-30', '2009-12-31', '2010-01-31', '2010-02-28', '2010-03-31', '2010-04-30', '2010-05-31', '2010-06-30', '2010-07-31', '2010-08-31', '2010-09-30', '2010-10-31', '2010-11-30', '2010-12-31', '2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30', '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31', '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31', '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31', '2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30', '2013-05-31', '2013-06-30', '2013-07-31', '2013-08-31', '2013-09-30', '2013-10-31', '2013-11-30', '2013-12-31', '2014-01-31', '2014-02-28', '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31', '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28']

,RegionID,SizeRank,RegionName,RegionType,StateName,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
0,102001,0,United States,country,NaN,170500.0,175000.0,177000.0,180000.0,185000.0,...,369900.0,375000.0,370000.0,368000.0,360000.0,362500.0,360000.0,357597.0,350000.0,362412.0
1,394913,1,"New York, NY",msa,NY,399950.0,390000.0,390000.0,392000.0,400000.0,...,650000.0,685000.0,686000.0,685000.0,660000.0,654250.0,661000.0,650000.0,665000.0,649082.0
2,753899,2,"Los Angeles, CA",msa,CA,470000.0,455000.0,458000.0,440000.0,435000.0,...,980000.0,1000000.0,960000.0,949000.0,955000.0,945000.0,945000.0,925000.0,920000.0,948780.0
3,394463,3,"Chicago, IL",msa,IL,219000.0,220000.0,223000.0,229000.0,235000.0,...,337250.0,350000.0,340000.0,340000.0,325000.0,325000.0,324500.0,316205.0,315000.0,328653.0
4,394514,4,"Dallas, TX",msa,TX,138000.0,145500.0,145000.0,150000.0,156000.0,...,400000.0,409000.0,400000.0,387000.0,380000.0,380000.0,374903.0,370000.0,370000.0,380064.0

In [7]:
id_cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]
date_cols = [c for c in msp.columns if c not in id_cols]

msp_long = msp.melt(
    id_vars=id_cols,
    value_vars=date_cols,
    var_name="month",
    value_name="median_sale_price"
)

msp_long["month"] = pd.to_datetime(msp_long["month"])
msp_long["median_sale_price"] = pd.to_numeric(msp_long["median_sale_price"], errors="coerce")

msp_long = msp_long.rename(columns={"RegionName": "metro"})
msp_long = msp_long[msp_long["metro"] != "United States"].copy()
msp_long = msp_long[["metro", "StateName", "month", "median_sale_price"]]

msp_long.head()

             metro StateName      month  median_sale_price
1     New York, NY        NY 2008-02-29           399950.0
2  Los Angeles, CA        CA 2008-02-29           470000.0
3      Chicago, IL        IL 2008-02-29           219000.0
4       Dallas, TX        TX 2008-02-29           138000.0
5      Houston, TX        TX 2008-02-29           145000.0

In [8]:
print("ZHVI metros:", zhvi_long["metro"].nunique())
print("MSP metros:", msp_long["metro"].nunique())

print("ZHVI date range:", zhvi_long["month"].min(), "to", zhvi_long["month"].max())
print("MSP date range:", msp_long["month"].min(), "to", msp_long["month"].max())

ZHVI metros: 894
MSP metros: 300
ZHVI date range: 2000-01-31 00:00:00 to 2026-02-28 00:00:00
MSP date range: 2008-02-29 00:00:00 to 2026-02-28 00:00:00

In [9]:
zhvi_keys = zhvi_long[["metro", "month"]].drop_duplicates()
msp_keys = msp_long[["metro", "month"]].drop_duplicates()

overlap = zhvi_keys.merge(msp_keys, on=["metro", "month"], how="inner")

print("ZHVI metro-month rows:", len(zhvi_keys))
print("MSP metro-month rows:", len(msp_keys))
print("Overlapping metro-month rows:", len(overlap))
print("Overlapping metros:", overlap["metro"].nunique())

ZHVI metro-month rows: 280716
MSP metro-month rows: 65100
Overlapping metro-month rows: 64232
Overlapping metros: 296

In [10]:
metro_core = zhvi_long.merge(
    msp_long,
    on=["metro", "StateName", "month"],
    how="inner"
)

print("Rows:", len(metro_core))
print("Unique metros:", metro_core["metro"].nunique())
print("Date range:", metro_core["month"].min(), "to", metro_core["month"].max())

metro_core.head()

Rows: 64232
Unique metros: 296
Date range: 2008-02-29 00:00:00 to 2026-02-28 00:00:00

             metro StateName      month           zhvi  median_sale_price
0     New York, NY        NY 2008-02-29  451918.962286           399950.0
1  Los Angeles, CA        CA 2008-02-29  530465.871660           470000.0
2      Chicago, IL        IL 2008-02-29  244118.221363           219000.0
3       Dallas, TX        TX 2008-02-29  157371.972478           138000.0
4      Houston, TX        TX 2008-02-29  156754.232492           145000.0

In [11]:
sales_path = "../data/raw/zillow/Metro_sales_count_now_uc_sfrcondo_month.csv"
sales = pd.read_csv(sales_path)

print("Shape:", sales.shape)
print("\nColumns:")
print(sales.columns.tolist())

sales.head()

Shape: (301, 222)

Columns:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', '2008-02-29', '2008-03-31', '2008-04-30', '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31', '2008-09-30', '2008-10-31', '2008-11-30', '2008-12-31', '2009-01-31', '2009-02-28', '2009-03-31', '2009-04-30', '2009-05-31', '2009-06-30', '2009-07-31', '2009-08-31', '2009-09-30', '2009-10-31', '2009-11-30', '2009-12-31', '2010-01-31', '2010-02-28', '2010-03-31', '2010-04-30', '2010-05-31', '2010-06-30', '2010-07-31', '2010-08-31', '2010-09-30', '2010-10-31', '2010-11-30', '2010-12-31', '2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30', '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31', '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31', '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31', '2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30', '2013-05-31', '2013-06-30', '2013-07-31', '2013-08-31', '2013-09-30', '2013-10-31', '2013-11-30', '2013-12-31', '2014-01-31', '2014-02-28', '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31', '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28']

,RegionID,SizeRank,RegionName,RegionType,StateName,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
0,102001,0,United States,country,NaN,203871.0,235974.0,261775.0,288739.0,301809.0,...,351859.0,359351.0,357221.0,341314.0,326624.0,331619.0,263573.0,301883.0,212896.0,229808.0
1,394913,1,"New York, NY",msa,NY,8530.0,9053.0,10042.0,10472.0,11324.0,...,12433.0,13588.0,14841.0,14367.0,13791.0,13624.0,11124.0,13337.0,9449.0,8140.0
2,753899,2,"Los Angeles, CA",msa,CA,4138.0,5049.0,6077.0,6864.0,7220.0,...,6720.0,6622.0,6984.0,6503.0,6643.0,7003.0,5393.0,6131.0,4435.0,4926.0
3,394463,3,"Chicago, IL",msa,IL,5606.0,6961.0,7320.0,7991.0,8818.0,...,9537.0,10413.0,10153.0,9270.0,8540.0,8770.0,6575.0,7469.0,5274.0,5947.0
4,394514,4,"Dallas, TX",msa,TX,4921.0,5585.0,6033.0,6727.0,6716.0,...,7205.0,7072.0,7155.0,6582.0,6054.0,6035.0,4727.0,5729.0,4077.0,4872.0

In [12]:
id_cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]
date_cols = [c for c in sales.columns if c not in id_cols]

sales_long = sales.melt(
    id_vars=id_cols,
    value_vars=date_cols,
    var_name="month",
    value_name="sales_count"
)

sales_long["month"] = pd.to_datetime(sales_long["month"])
sales_long["sales_count"] = pd.to_numeric(sales_long["sales_count"], errors="coerce")

sales_long = sales_long.rename(columns={"RegionName": "metro"})
sales_long = sales_long[sales_long["metro"] != "United States"].copy()
sales_long = sales_long[["metro", "StateName", "month", "sales_count"]]

sales_long.head()

             metro StateName      month  sales_count
1     New York, NY        NY 2008-02-29       8530.0
2  Los Angeles, CA        CA 2008-02-29       4138.0
3      Chicago, IL        IL 2008-02-29       5606.0
4       Dallas, TX        TX 2008-02-29       4921.0
5      Houston, TX        TX 2008-02-29       4100.0

In [13]:
metro_core = metro_core.merge(
    sales_long,
    on=["metro", "StateName", "month"],
    how="inner"
)

print("Rows:", len(metro_core))
print("Unique metros:", metro_core["metro"].nunique())
print("Date range:", metro_core["month"].min(), "to", metro_core["month"].max())

metro_core.head()

Rows: 64232
Unique metros: 296
Date range: 2008-02-29 00:00:00 to 2026-02-28 00:00:00

,metro,StateName,month,zhvi,median_sale_price,sales_count
0,"New York, NY",NY,2008-02-29,451918.962286,399950.0,8530.0
1,"Los Angeles, CA",CA,2008-02-29,530465.871660,470000.0,4138.0
2,"Chicago, IL",IL,2008-02-29,244118.221363,219000.0,5606.0
3,"Dallas, TX",TX,2008-02-29,157371.972478,138000.0,4921.0
4,"Houston, TX",TX,2008-02-29,156754.232492,145000.0,4100.0

In [14]:
new_con_sales_path = "../data/raw/zillow/Metro_new_con_sales_count_raw_uc_sfrcondo_month.csv"
new_con_sales = pd.read_csv(new_con_sales_path)

print("Shape:", new_con_sales.shape)
print("\nColumns:")
print(new_con_sales.columns.tolist())

new_con_sales.head()

Shape: (363, 102)

Columns:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31']

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,...,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31
0,102001,0,United States,country,NaN,44893.0,46859.0,61753.0,57809.0,64185.0,...,50962.0,55360.0,51811.0,47458.0,48178.0,47732.0,44799.0,39921.0,50162.0,29393.0
1,394913,1,"New York, NY",msa,NY,603.0,520.0,615.0,595.0,712.0,...,393.0,413.0,410.0,400.0,506.0,428.0,461.0,389.0,417.0,287.0
2,753899,2,"Los Angeles, CA",msa,CA,487.0,519.0,864.0,653.0,761.0,...,193.0,249.0,200.0,207.0,206.0,240.0,215.0,204.0,234.0,145.0
3,394463,3,"Chicago, IL",msa,IL,419.0,331.0,528.0,555.0,639.0,...,538.0,553.0,500.0,488.0,555.0,563.0,531.0,531.0,499.0,339.0
4,394514,4,"Dallas, TX",msa,TX,1562.0,1706.0,2383.0,2275.0,2382.0,...,2115.0,2541.0,2376.0,2266.0,2134.0,2244.0,1985.0,1929.0,2667.0,1384.0

In [15]:
id_cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]
date_cols = [c for c in new_con_sales.columns if c not in id_cols]

new_con_sales_long = new_con_sales.melt(
    id_vars=id_cols,
    value_vars=date_cols,
    var_name="month",
    value_name="new_con_sales_count"
)

new_con_sales_long["month"] = pd.to_datetime(new_con_sales_long["month"])
new_con_sales_long["new_con_sales_count"] = pd.to_numeric(
    new_con_sales_long["new_con_sales_count"], errors="coerce"
)

new_con_sales_long = new_con_sales_long.rename(columns={"RegionName": "metro"})
new_con_sales_long = new_con_sales_long[new_con_sales_long["metro"] != "United States"].copy()
new_con_sales_long = new_con_sales_long[["metro", "StateName", "month", "new_con_sales_count"]]

new_con_sales_long.head()

             metro StateName      month  new_con_sales_count
1     New York, NY        NY 2018-01-31                603.0
2  Los Angeles, CA        CA 2018-01-31                487.0
3      Chicago, IL        IL 2018-01-31                419.0
4       Dallas, TX        TX 2018-01-31               1562.0
5      Houston, TX        TX 2018-01-31               1514.0

In [16]:
metro_core = metro_core.merge(
    new_con_sales_long,
    on=["metro", "StateName", "month"],
    how="inner"
)

print("Rows:", len(metro_core))
print("Unique metros:", metro_core["metro"].nunique())
print("Date range:", metro_core["month"].min(), "to", metro_core["month"].max())

metro_core.head()

Rows: 25123
Unique metros: 259
Date range: 2018-01-31 00:00:00 to 2026-01-31 00:00:00

,metro,StateName,month,zhvi,median_sale_price,sales_count,new_con_sales_count
0,"New York, NY",NY,2018-01-31,466310.168138,375000.0,14471.0,603.0
1,"Los Angeles, CA",CA,2018-01-31,599666.830440,588000.0,6835.0,487.0
2,"Chicago, IL",IL,2018-01-31,224146.687795,208500.0,7428.0,419.0
3,"Dallas, TX",TX,2018-01-31,239766.128308,235000.0,5278.0,1562.0
4,"Houston, TX",TX,2018-01-31,209541.291859,203393.0,4730.0,1514.0

In [17]:
new_con_price_path = "../data/raw/zillow/Metro_new_con_median_sale_price_uc_sfrcondo_month.csv"
new_con_price = pd.read_csv(new_con_price_path)

print("Shape:", new_con_price.shape)
print("\nColumns:")
print(new_con_price.columns.tolist())

new_con_price.head()

Shape: (174, 102)

Columns:
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31']

,RegionID,SizeRank,RegionName,RegionType,StateName,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,...,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31
0,102001,0,United States,country,NaN,299997.0,301500.0,308315.0,305924.0,312186.0,...,423000.0,416872.5,419935.0,416870.00,415000.0,415000.0,425000.0,419980.0,415000.0,410000.0
1,394913,1,"New York, NY",msa,NY,577855.0,615860.0,582621.0,610000.0,620000.0,...,883360.0,875000.0,893625.0,872500.00,1055000.0,982611.0,975000.0,987702.0,977500.0,971925.5
2,753899,2,"Los Angeles, CA",msa,CA,845000.0,821500.0,839000.0,881500.0,939000.0,...,1522500.0,1330000.0,1125000.0,1400000.00,1127990.0,940000.0,1250000.0,1040000.0,1033495.0,1437500.0
3,394463,3,"Chicago, IL",msa,IL,340000.0,362000.0,348500.0,339226.0,366500.0,...,469990.0,457950.0,479907.0,483484.75,444990.0,432990.0,455000.0,462323.0,451645.0,434990.0
4,394514,4,"Dallas, TX",msa,TX,324266.0,319900.0,320000.0,314951.5,329157.0,...,404050.0,385000.0,390000.0,387490.00,380000.0,390916.5,394990.0,375000.0,380000.0,386750.0

In [18]:
id_cols = ["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"]
date_cols = [c for c in new_con_price.columns if c not in id_cols]

new_con_price_long = new_con_price.melt(
    id_vars=id_cols,
    value_vars=date_cols,
    var_name="month",
    value_name="new_con_median_sale_price"
)

new_con_price_long["month"] = pd.to_datetime(new_con_price_long["month"])
new_con_price_long["new_con_median_sale_price"] = pd.to_numeric(
    new_con_price_long["new_con_median_sale_price"], errors="coerce"
)

new_con_price_long = new_con_price_long.rename(columns={"RegionName": "metro"})
new_con_price_long = new_con_price_long[new_con_price_long["metro"] != "United States"].copy()
new_con_price_long = new_con_price_long[["metro", "StateName", "month", "new_con_median_sale_price"]]

new_con_price_long.head()

             metro StateName      month  new_con_median_sale_price
1     New York, NY        NY 2018-01-31                   577855.0
2  Los Angeles, CA        CA 2018-01-31                   845000.0
3      Chicago, IL        IL 2018-01-31                   340000.0
4       Dallas, TX        TX 2018-01-31                   324266.0
5      Houston, TX        TX 2018-01-31                   279000.0

In [19]:
metro_core_full = metro_core.merge(
    new_con_price_long,
    on=["metro", "StateName", "month"],
    how="inner"
)

print("Rows:", len(metro_core_full))
print("Unique metros:", metro_core_full["metro"].nunique())
print("Date range:", metro_core_full["month"].min(), "to", metro_core_full["month"].max())

metro_core_full.head()

Rows: 15908
Unique metros: 164
Date range: 2018-01-31 00:00:00 to 2026-01-31 00:00:00

,metro,StateName,month,zhvi,median_sale_price,sales_count,new_con_sales_count,new_con_median_sale_price
0,"New York, NY",NY,2018-01-31,466310.168138,375000.0,14471.0,603.0,577855.0
1,"Los Angeles, CA",CA,2018-01-31,599666.830440,588000.0,6835.0,487.0,845000.0
2,"Chicago, IL",IL,2018-01-31,224146.687795,208500.0,7428.0,419.0,340000.0
3,"Dallas, TX",TX,2018-01-31,239766.128308,235000.0,5278.0,1562.0,324266.0
4,"Houston, TX",TX,2018-01-31,209541.291859,203393.0,4730.0,1514.0,279000.0

In [20]:
metro_core_full = metro_core_full.sort_values(["metro", "month"]).copy()

metro_core_full["zhvi_yoy_growth"] = (
    metro_core_full.groupby("metro")["zhvi"].pct_change(12) * 100
)

metro_core_full["median_sale_price_yoy_growth"] = (
    metro_core_full.groupby("metro")["median_sale_price"].pct_change(12) * 100
)

metro_core_full["sales_count_yoy_growth"] = (
    metro_core_full.groupby("metro")["sales_count"].pct_change(12) * 100
)

metro_core_full["new_con_sales_yoy_growth"] = (
    metro_core_full.groupby("metro")["new_con_sales_count"].pct_change(12) * 100
)

metro_core_full["new_con_price_premium"] = (
    metro_core_full["new_con_median_sale_price"] / metro_core_full["median_sale_price"]
)

metro_core_full["new_con_share_of_sales"] = (
    metro_core_full["new_con_sales_count"] / metro_core_full["sales_count"]
)

metro_core_full.head(15)

,metro,StateName,month,zhvi,median_sale_price,sales_count,new_con_sales_count,new_con_median_sale_price,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales
151,"Abilene, TX",TX,2018-01-31,134892.043832,144800.0,122.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,0.188525
315,"Abilene, TX",TX,2018-02-28,135414.271576,142692.0,119.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,0.310924
479,"Abilene, TX",TX,2018-03-31,136226.793115,147000.0,190.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,0.210526
643,"Abilene, TX",TX,2018-04-30,137007.738177,155333.0,215.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,0.102326
807,"Abilene, TX",TX,2018-05-31,137985.666163,158000.0,240.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,0.137500
971,"Abilene, TX",TX,2018-06-30,138810.337032,151950.0,247.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN,0.129555
1135,"Abilene, TX",TX,2018-07-31,139707.056385,142750.0,245.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,0.118367
1299,"Abilene, TX",TX,2018-08-31,140569.763679,142700.0,234.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,0.145299
1463,"Abilene, TX",TX,2018-09-30,141353.389516,169950.0,180.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN,0.227778
1627,"Abilene, TX",TX,2018-10-31,141940.206955,158000.0,162.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,0.092593
1791,"Abilene, TX",TX,2018-11-30,142478.671399,157450.0,143.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,0.125874
1955,"Abilene, TX",TX,2018-12-31,142889.205091,166103.0,139.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,0.179856
2119,"Abilene, TX",TX,2019-01-31,142966.796465,139950.0,112.0,16.0,NaN,5.986085,-3.349448,-8.196721,-30.434783,NaN,0.142857
2283,"Abilene, TX",TX,2019-02-28,142755.096410,150000.0,151.0,19.0,NaN,5.421013,5.121520,26.890756,-48.648649,NaN,0.125828
2447,"Abilene, TX",TX,2019-03-31,142670.254279,154450.0,187.0,27.0,NaN,4.729951,5.068027,-1.578947,-32.500000,NaN,0.144385

In [21]:
metro_core_full[[
    "zhvi",
    "median_sale_price",
    "sales_count",
    "new_con_sales_count",
    "new_con_median_sale_price",
    "zhvi_yoy_growth",
    "median_sale_price_yoy_growth",
    "sales_count_yoy_growth",
    "new_con_sales_yoy_growth",
    "new_con_price_premium",
    "new_con_share_of_sales"
]].isna().sum()

zhvi                               3
median_sale_price                  0
sales_count                        9
new_con_sales_count               49
new_con_median_sale_price       1320
zhvi_yoy_growth                 1974
median_sale_price_yoy_growth    1968
sales_count_yoy_growth          1984
new_con_sales_yoy_growth        2019
new_con_price_premium           1320
new_con_share_of_sales            58
dtype: int64

In [22]:
latest_month = metro_core_full["month"].max()
print("Latest month:", latest_month)

recent = metro_core_full[
    metro_core_full["month"] >= (latest_month - pd.DateOffset(months=12))
].copy()

metro_summary = recent.groupby(["metro", "StateName"], as_index=False).agg({
    "zhvi": "last",
    "median_sale_price": "last",
    "sales_count": "mean",
    "new_con_sales_count": "mean",
    "new_con_median_sale_price": "mean",
    "zhvi_yoy_growth": "mean",
    "median_sale_price_yoy_growth": "mean",
    "sales_count_yoy_growth": "mean",
    "new_con_sales_yoy_growth": "mean",
    "new_con_price_premium": "mean",
    "new_con_share_of_sales": "mean"
})

print("Rows:", len(metro_summary))
metro_summary.head()

Latest month: 2026-01-31 00:00:00
Rows: 164

,metro,StateName,zhvi,median_sale_price,sales_count,new_con_sales_count,new_con_median_sale_price,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales
0,"Abilene, TX",TX,202082.359468,252500.0,192.076923,45.615385,273009.115385,0.658658,4.913783,23.544810,68.656175,1.132510,0.236867
1,"Albany, NY",NY,350212.228772,325000.0,662.307692,44.923077,643901.230769,4.237814,5.699661,3.600987,10.172208,1.945686,0.069436
2,"Albuquerque, NM",NM,341890.903058,340000.0,732.076923,80.538462,405532.269231,2.232991,2.054839,2.333311,-5.667514,1.156273,0.110234
3,"Allentown, PA",PA,348992.033054,326875.0,934.000000,58.615385,496403.615385,3.578114,6.613389,-3.570304,-18.736855,1.514172,0.063167
4,"Ann Arbor, MI",MI,404020.148933,360000.0,326.384615,32.076923,527501.666667,2.353295,3.387916,7.223360,15.921709,1.394831,0.103822

In [23]:
cluster_features = [
    "zhvi_yoy_growth",
    "median_sale_price_yoy_growth",
    "sales_count_yoy_growth",
    "new_con_sales_yoy_growth",
    "new_con_price_premium",
    "new_con_share_of_sales"
]

metro_cluster_data = metro_summary[["metro", "StateName"] + cluster_features].copy()
metro_cluster_data = metro_cluster_data.dropna().reset_index(drop=True)

print("Rows after dropna:", len(metro_cluster_data))
metro_cluster_data.head()

Rows after dropna: 164

,metro,StateName,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales
0,"Abilene, TX",TX,0.658658,4.913783,23.544810,68.656175,1.132510,0.236867
1,"Albany, NY",NY,4.237814,5.699661,3.600987,10.172208,1.945686,0.069436
2,"Albuquerque, NM",NM,2.232991,2.054839,2.333311,-5.667514,1.156273,0.110234
3,"Allentown, PA",PA,3.578114,6.613389,-3.570304,-18.736855,1.514172,0.063167
4,"Ann Arbor, MI",MI,2.353295,3.387916,7.223360,15.921709,1.394831,0.103822

In [25]:
from sklearn.preprocessing import StandardScaler

X = metro_cluster_data[[
    "zhvi_yoy_growth",
    "median_sale_price_yoy_growth",
    "sales_count_yoy_growth",
    "new_con_sales_yoy_growth",
    "new_con_price_premium",
    "new_con_share_of_sales"
]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled shape:", X_scaled.shape)
X_scaled[:5]

Scaled shape: (164, 6)

array([[ 0.06691888,  0.65040713,  3.9900413 ,  5.03292486, -0.53175834,
         0.01849269],
       [ 1.39357304,  0.90452445,  0.207261  ,  1.11251916,  3.02201819,
        -1.0813473 ],
       [ 0.65046295, -0.27404634, -0.03318144,  0.05072158, -0.42790654,
        -0.81334841],
       [ 1.14904775,  1.19998304, -1.15293048, -0.82536672,  1.13620043,
        -1.12252513],
       [ 0.69505479,  0.15701077,  0.89432283,  1.49793036,  0.61464716,
        -0.85546451]])

In [26]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

results = []

for k in range(2, 7):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    results.append((k, score))

results

[(2, 0.24707684703747962),
 (3, 0.218995551830352),
 (4, 0.18780119996842856),
 (5, 0.18883345229989174),
 (6, 0.17328187902219985)]

In [27]:
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
metro_cluster_data["cluster"] = kmeans.fit_predict(X_scaled)

metro_cluster_data.head()

,metro,StateName,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales,cluster
0,"Abilene, TX",TX,0.658658,4.913783,23.544810,68.656175,1.132510,0.236867,0
1,"Albany, NY",NY,4.237814,5.699661,3.600987,10.172208,1.945686,0.069436,1
2,"Albuquerque, NM",NM,2.232991,2.054839,2.333311,-5.667514,1.156273,0.110234,2
3,"Allentown, PA",PA,3.578114,6.613389,-3.570304,-18.736855,1.514172,0.063167,1
4,"Ann Arbor, MI",MI,2.353295,3.387916,7.223360,15.921709,1.394831,0.103822,1

In [28]:
cluster_profile = metro_cluster_data.groupby("cluster").agg({
    "zhvi_yoy_growth": "mean",
    "median_sale_price_yoy_growth": "mean",
    "sales_count_yoy_growth": "mean",
    "new_con_sales_yoy_growth": "mean",
    "new_con_price_premium": "mean",
    "new_con_share_of_sales": "mean"
}).round(2)

cluster_profile

,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales
cluster,,,,,,
0,-0.16,2.11,2.42,4.33,1.12,0.41
1,2.46,5.44,1.04,-6.64,1.47,0.14
2,-1.28,0.63,4.26,-14.63,1.12,0.21

In [29]:
metro_core_final = metro_core_full.merge(
    metro_cluster_data[["metro", "StateName", "cluster"]],
    on=["metro", "StateName"],
    how="left"
)

metro_core_final.head()

,metro,StateName,month,zhvi,median_sale_price,sales_count,new_con_sales_count,new_con_median_sale_price,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales,cluster
0,"Abilene, TX",TX,2018-01-31,134892.043832,144800.0,122.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,0.188525,0
1,"Abilene, TX",TX,2018-02-28,135414.271576,142692.0,119.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,0.310924,0
2,"Abilene, TX",TX,2018-03-31,136226.793115,147000.0,190.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,0.210526,0
3,"Abilene, TX",TX,2018-04-30,137007.738177,155333.0,215.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,0.102326,0
4,"Abilene, TX",TX,2018-05-31,137985.666163,158000.0,240.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,0.137500,0

In [30]:
metro_summary_final = metro_summary.merge(
    metro_cluster_data[["metro", "StateName", "cluster"]],
    on=["metro", "StateName"],
    how="left"
)

metro_summary_final.head()

,metro,StateName,zhvi,median_sale_price,sales_count,new_con_sales_count,new_con_median_sale_price,zhvi_yoy_growth,median_sale_price_yoy_growth,sales_count_yoy_growth,new_con_sales_yoy_growth,new_con_price_premium,new_con_share_of_sales,cluster
0,"Abilene, TX",TX,202082.359468,252500.0,192.076923,45.615385,273009.115385,0.658658,4.913783,23.544810,68.656175,1.132510,0.236867,0
1,"Albany, NY",NY,350212.228772,325000.0,662.307692,44.923077,643901.230769,4.237814,5.699661,3.600987,10.172208,1.945686,0.069436,1
2,"Albuquerque, NM",NM,341890.903058,340000.0,732.076923,80.538462,405532.269231,2.232991,2.054839,2.333311,-5.667514,1.156273,0.110234,2
3,"Allentown, PA",PA,348992.033054,326875.0,934.000000,58.615385,496403.615385,3.578114,6.613389,-3.570304,-18.736855,1.514172,0.063167,1
4,"Ann Arbor, MI",MI,404020.148933,360000.0,326.384615,32.076923,527501.666667,2.353295,3.387916,7.223360,15.921709,1.394831,0.103822,1

In [31]:
metro_core_final.to_csv("../data/processed/metro_core_final.csv", index=False)
metro_summary_final.to_csv("../data/processed/metro_summary_final.csv", index=False)

print("Files saved successfully.")

Files saved successfully.